name: Build and Publish Docker Image

env:
    GO_VERSION: '1.22.4'
    SERVICE_NAME: 'service-template'
    ALPINE_VERSION: '3.20'

on:
  push:
    tags:
      - '*'
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # v3.10.0

    - name: Optionally, login to Docker repository
      uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      if: env.DOCKER_USERNAME != null
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@471d1dc4e07e5cdedd4c2171150001c434f0b7a4 # v6.15.0
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ vars.DOCKER_REGISTRY_ACCOUNT }}/${{ env.SERVICE_NAME }}:${{ github.ref_name }}
        build-args: |
          GO_VERSION=${{ env.GO_VERSION }}
          ALPINE_VERSION=${{ env.ALPINE_VERSION }}
          SERVICE_NAME=${{ env.SERVICE_NAME }}
        labels: |
          org.opencontainers.image.source=https://github.com/uclalibrary/${{ env.SERVICE_NAME }}
          org.opencontainers.image.description=UCLA Library's ${{ env.SERVICE_NAME }}
